const STATUS_ARR = {
	NONE: 'NONE',
	SUCCESS: 'SUCCESS',
	SKIPPED: 'SKIP',
	PAYMENT_PENDING: 'PAYMENT_PENDING',
	PENDING: 'PENDING',
	FAILED: 'FAILED',
	FAILURE: 'FAILURE'
};

export const ORDER_STATUS = {
	ORDER_PROCESSING: 'ORDER_PROCESSING',
	ORDER_SCHEDULED: 'ORDER_SCHEDULED',
	ORDER_REJECTED: 'ORDER_REJECTED',
	ORDER_CREATED: 'ORDER_CREATED',
	ORDER_COMPLETE: 'ORDER_COMPLETE'
};
export default STATUS_ARR;
