const STATUS_ARR = {
	NONE: 'NONE',
	SUCCESS: 'SUCCESS',
	SKIPPED: 'SKIP',
	PAYMENT_PENDING: 'PAYMENT_PENDING',
	PENDING: 'PENDING',
	FAILED: 'FAILED',
	FAILURE: 'FAILURE',
	EDITED: 'EDIT'
};

export const ORDER_STATUS = {
	ORDER_PROCESSING: 'ORDER_PROCESSING',
	ORDER_SCHEDULED: 'ORDER_SCHEDULED',
	ORDER_REJECTED: 'ORDER_REJECTED',
	ORDER_CREATED: 'ORDER_CREATED',
	ORDER_COMPLETE: 'ORDER_COMPLETE'
};

export const ORDER_STATUS_MAP = {
	[ORDER_STATUS.ORDER_PROCESSING]: 'In progress',
	[ORDER_STATUS.ORDER_REJECTED]: 'Failed',
	[ORDER_STATUS.ORDER_COMPLETE]: 'Completed'
};

export default STATUS_ARR;
