const STATUS_ARR = {
	NONE: 'NONE',
	SUCCESS: 'SUCCESS',
	SKIPPED: 'SKIP',
	PAYMENT_PENDING: 'PAYMENT_PENDING',
	PENDING: 'PENDING',
	FAILED: 'FAILED',
	FAILURE: 'FAILURE'
};
export default STATUS_ARR;
